name: netcdf
channels:
  - http://conda.binstar.org/omnia
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0=py36_1000
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py_0
  - bleach=3.1.0=py_0
  - bzip2=1.0.8=h01d97ff_1
  - ca-certificates=2019.11.28=hecc5488_0
  - certifi=2019.11.28=py36_0
  - cftime=1.0.4.2=py36h3b54f70_0
  - curl=7.65.3=h22ea746_0
  - cycler=0.10.0=py_2
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py36_1000
  - freetype=2.10.0=h24853df_1
  - hdf4=4.2.13=h84186c3_1003
  - hdf5=1.10.5=nompi_h3e39495_1104
  - icu=58.2=h0a44026_1000
  - importlib_metadata=1.2.0=py36_0
  - ipykernel=5.1.3=py36h5ca1d4c_0
  - ipython=7.10.1=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=py_0
  - jedi=0.15.1=py36_0
  - jinja2=2.10.3=py_0
  - jpeg=9c=h1de35cc_1001
  - jsonschema=3.2.0=py36_0
  - jupyter=1.0.0=py_2
  - jupyter_client=5.3.3=py36_1
  - jupyter_console=5.1.0=py36_0
  - jupyter_core=4.6.1=py36_0
  - kiwisolver=1.1.0=py36ha1b3eb9_0
  - krb5=1.16.3=hcfa6398_1001
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libcurl=7.65.3=h16faf7d_0
  - libcxx=9.0.0=h89e68fa_1
  - libedit=3.1.20170329=hcfe32e1_1001
  - libffi=3.2.1=h6de7cb9_1006
  - libgfortran=4.0.0=2
  - liblapack=3.8.0=14_openblas
  - libnetcdf=4.7.1=nompi_hec86efb_102
  - libopenblas=0.3.7=h3d69b6c_4
  - libpng=1.6.37=h2573ce8_0
  - libsodium=1.0.17=h01d97ff_0
  - libssh2=1.8.2=hcdc9a53_2
  - llvm-openmp=8.0.1=h770b8ee_0
  - markupsafe=1.1.1=py36h0b31af3_0
  - matplotlib=3.1.2=py36_1
  - matplotlib-base=3.1.2=py36h11da6c2_1
  - mistune=0.8.4=py36h0b31af3_1000
  - more-itertools=8.0.1=py_0
  - nbconvert=5.6.1=py36_0
  - nbformat=4.4.0=py_1
  - ncurses=6.1=h0a44026_1002
  - netcdf4=1.5.3=nompi_py36hd261794_101
  - notebook=6.0.1=py36_0
  - numpy=1.17.3=py36hde6bac1_0
  - openssl=1.1.1d=h0b31af3_0
  - pandas=0.25.3=py36h4f17bb1_0
  - pandoc=2.8.1=0
  - pandocfilters=1.4.2=py_1
  - parso=0.5.1=py_0
  - patsy=0.5.1=py_0
  - pexpect=4.7.0=py36_0
  - pickleshare=0.7.5=py36_1000
  - pip=19.3.1=py36_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=3.0.2=py_0
  - ptyprocess=0.6.0=py_1001
  - pygments=2.5.2=py_0
  - pyparsing=2.4.5=py_0
  - pyqt=5.6.0=py36hc26a216_1008
  - pyrsistent=0.15.6=py36h0b31af3_0
  - python=3.6.7=h4285619_1006
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - pyzmq=18.1.1=py36h4bf09a9_0
  - qt=5.6.2=h822fa55_1013
  - qtconsole=4.6.0=py_0
  - readline=8.0=hcfe32e1_0
  - scipy=1.3.2=py36h82752d6_0
  - seaborn=0.9.0=py_2
  - send2trash=1.5.0=py_0
  - setuptools=42.0.2=py36_0
  - sip=4.18.1=py36h0a44026_1000
  - six=1.13.0=py36_0
  - sqlite=3.30.1=h93121df_0
  - statsmodels=0.10.2=py36h3b54f70_0
  - terminado=0.8.3=py36_0
  - testpath=0.4.4=py_0
  - tk=8.6.10=hbbe82c9_0
  - tornado=6.0.3=py36h0b31af3_0
  - traitlets=4.3.3=py36_0
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - wheel=0.33.6=py36_0
  - widgetsnbextension=3.5.1=py36_0
  - xz=5.2.4=h1de35cc_1001
  - zeromq=4.3.2=h6de7cb9_2
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h0b31af3_1006
prefix: /Users/toni_brain/miniconda3/envs/netcdf

